version: "3.9"

services:
  oniriko-bd:
    build:
      context: ../oniriko-bbdd
      dockerfile: ../oniriko-bbdd/Dockerfile
    container_name: oniriko-db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ../oniriko-bbdd/.env

  oniriko-backend:
    build:
      context: ../oniriko-backend
      dockerfile: ../oniriko-backend/Dockerfile
    container_name: oniriko-backend
    restart: always
    depends_on:
      - oniriko-bd
    ports:
      - "8080:8080"

networks:
  net: