
services:
  oniriko-bd:
    build:
      context: ../oniriko-bbdd
      dockerfile: ../oniriko-bbdd/Dockerfile
    image: oniriko-bbdd:${IMAGE_VERSION}
    container_name: oniriko-db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ../oniriko-bbdd/.env
    networks:
      - net

  oniriko-backend:
    build:
      context: ../oniriko-backend
      dockerfile: ../oniriko-backend/Dockerfile
    image: oniriko-backend:${IMAGE_VERSION}
    container_name: oniriko-backend
    restart: always
    depends_on:
      - oniriko-bd
    ports:
      - "8080:8080"
    networks:
      - net

  oniriko-frontend:
    build:
      context: ../oniriko-frontend
      dockerfile: ../oniriko-frontend/Dockerfile
    image: oniriko-frontend:${IMAGE_VERSION}
    container_name: oniriko-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - oniriko-backend
    networks:
      - net

networks:
  net:
    driver: bridge
